import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import test from 'node:test';

test('admin UI exposes a sales pipeline workspace with notes, estimates, and rediagnosis history', async () => {
  const html = await readFile('public/admin.html', 'utf8');

  assert.match(html, /영업 파이프라인/);
  assert.match(html, /상담 이력/);
  assert.match(html, /견적 상태/);
  assert.match(html, /재진단 히스토리/);
  assert.match(html, /data-pipeline-board/);
  assert.match(html, /admin-main/);
  assert.match(html, /admin-toolbar-panel/);
  assert.match(html, /admin-pipeline-panel/);
  assert.match(html, /admin-utility-panel/);
  assert.match(html, /운영 보안 점검/);
  assert.match(html, /분석 품질 벤치마크/);
  assert.match(html, /\/api\/admin\/security/);
  assert.match(html, /\/api\/admin\/quality-benchmark/);
  assert.match(html, /\/api\/admin\/notes/);
  assert.match(html, /\/api\/rediagnosis\/compare/);
  assert.match(html, /renderSalesNextActions/);
  assert.match(html, /renderLeadNextAction/);
  assert.match(html, /renderLeadOperationalDetail/);
  assert.match(html, /lead-detail-panel/);
  assert.match(html, /createEstimateForLead/);
  assert.match(html, /data-prefill-note/);
  assert.match(html, /renderPipelineLeadSummary/);
  assert.match(html, /renderLeadContactDetails/);
  assert.match(html, /labelForDesiredWork/);
  assert.match(html, /labelForTimeline/);
  assert.match(html, /신청자/);
  assert.match(html, /희망 작업/);
  assert.match(html, /진단 이슈/);
  assert.match(html, /findLatestRunForLead/);
  assert.match(html, /salesConversion/);
  assert.match(html, /data-demo-runner/);
  assert.match(html, /\/api\/admin\/demo-fixtures/);
  assert.match(html, /\/api\/admin\/demo-runs/);
  assert.match(html, /createDemoRun/);
  assert.match(html, /data-demo-scope-filter/);
  assert.match(html, /demo-scope-filter/);
  assert.match(html, /filteredRuns/);
  assert.match(html, /filteredEstimates/);
  assert.match(html, /isDemoRecord/);
  assert.match(html, /renderDemoRunResult/);
  assert.match(html, /renderSecurityStatus/);
  assert.match(html, /renderQualityBenchmark/);
  assert.match(html, /demoRunResult/);
  assert.match(html, /demo-report-link/);
  assert.match(html, /data-demo-cleanup/);
  assert.match(html, /\/api\/admin\/demo-data/);
  assert.match(html, /deleteDemoData/);
  assert.match(html, /DELETE_DEMO_DATA/);
  assert.match(html, /demo-scope-filter'\)\.value = 'demo'/);
  assert.match(html, /추천 패키지/);
});
